all: false
packages:
  expenses/internal/domain:
    interfaces:
      Repository:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          pkgname: "mocks"
          filename: "Repository.go"
