all: false
packages:
  expenses/internal/domain:
    interfaces:
      Repository:
        config:
          dir: testing/mocks
          pkgname: "mocks"
          filename: "mock_{{.InterfaceName | snakecase }}.go"

  expenses/internal/application/expense:
    interfaces:
      ServiceInterface:
        config:
          dir: testing/mocks
          pkgname: "mocks"
          filename: "mock_{{.InterfaceName | snakecase }}.go"

