// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID          int64
	Amount      pgtype.Numeric
	Category    string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	Budget      pgtype.Numeric
}
