// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
    amount,
    category,
    description,
    budget
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    amount,
    category,
    description,
    created_at,
    budget
`

type CreateExpenseParams struct {
	Amount      pgtype.Numeric
	Category    string
	Description pgtype.Text
	Budget      pgtype.Numeric
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.Amount,
		arg.Category,
		arg.Description,
		arg.Budget,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
		&i.Budget,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const getAllExpenses = `-- name: GetAllExpenses :many
SELECT
    id,
    amount,
    category,
    description,
    created_at,
    budget
FROM expenses
ORDER BY created_at DESC
`

func (q *Queries) GetAllExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getAllExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
			&i.Budget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllExpensesByAmount = `-- name: GetAllExpensesByAmount :many
SELECT
    id,
    amount,
    category,
    description,
    created_at,
    budget
FROM expenses
WHERE amount = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllExpensesByAmount(ctx context.Context, amount pgtype.Numeric) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getAllExpensesByAmount, amount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
			&i.Budget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllExpensesByCategory = `-- name: GetAllExpensesByCategory :many
SELECT
    id,
    amount,
    category,
    description,
    created_at,
    budget
FROM expenses
WHERE category = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllExpensesByCategory(ctx context.Context, category string) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getAllExpensesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
			&i.Budget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllExpensesByDate = `-- name: GetAllExpensesByDate :many
SELECT
    id,
    amount,
    category,
    description,
    created_at,
    budget
FROM expenses
WHERE created_at::date = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllExpensesByDate(ctx context.Context, createdAt pgtype.Timestamptz) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getAllExpensesByDate, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
			&i.Budget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT
    id,
    amount,
    category,
    description,
    created_at,
    budget
FROM expenses
WHERE id = $1
`

func (q *Queries) GetExpenseByID(ctx context.Context, id int64) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
		&i.Budget,
	)
	return i, err
}
