// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/expense.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Expense struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Amount      *string                `protobuf:"bytes,2,opt,name=amount"`
	xxx_hidden_Category    *string                `protobuf:"bytes,3,opt,name=category"`
	xxx_hidden_Description *string                `protobuf:"bytes,4,opt,name=description"`
	xxx_hidden_Budget      *string                `protobuf:"bytes,5,opt,name=budget"`
	xxx_hidden_CreatedAt   *string                `protobuf:"bytes,6,opt,name=created_at,json=createdAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Expense) Reset() {
	*x = Expense{}
	mi := &file_proto_expense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expense) ProtoMessage() {}

func (x *Expense) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Expense) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Expense) GetAmount() string {
	if x != nil {
		if x.xxx_hidden_Amount != nil {
			return *x.xxx_hidden_Amount
		}
		return ""
	}
	return ""
}

func (x *Expense) GetCategory() string {
	if x != nil {
		if x.xxx_hidden_Category != nil {
			return *x.xxx_hidden_Category
		}
		return ""
	}
	return ""
}

func (x *Expense) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *Expense) GetBudget() string {
	if x != nil {
		if x.xxx_hidden_Budget != nil {
			return *x.xxx_hidden_Budget
		}
		return ""
	}
	return ""
}

func (x *Expense) GetCreatedAt() string {
	if x != nil {
		if x.xxx_hidden_CreatedAt != nil {
			return *x.xxx_hidden_CreatedAt
		}
		return ""
	}
	return ""
}

func (x *Expense) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Expense) SetAmount(v string) {
	x.xxx_hidden_Amount = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *Expense) SetCategory(v string) {
	x.xxx_hidden_Category = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *Expense) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *Expense) SetBudget(v string) {
	x.xxx_hidden_Budget = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *Expense) SetCreatedAt(v string) {
	x.xxx_hidden_CreatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *Expense) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Expense) HasAmount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Expense) HasCategory() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Expense) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Expense) HasBudget() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Expense) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Expense) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *Expense) ClearAmount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Amount = nil
}

func (x *Expense) ClearCategory() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Category = nil
}

func (x *Expense) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Description = nil
}

func (x *Expense) ClearBudget() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Budget = nil
}

func (x *Expense) ClearCreatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_CreatedAt = nil
}

type Expense_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          *int64
	Amount      *string
	Category    *string
	Description *string
	Budget      *string
	CreatedAt   *string
}

func (b0 Expense_builder) Build() *Expense {
	m0 := &Expense{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Amount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Amount = b.Amount
	}
	if b.Category != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Category = b.Category
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Description = b.Description
	}
	if b.Budget != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Budget = b.Budget
	}
	if b.CreatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_CreatedAt = b.CreatedAt
	}
	return m0
}

type CreateExpenseRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Amount      *string                `protobuf:"bytes,1,opt,name=amount"`
	xxx_hidden_Category    *string                `protobuf:"bytes,2,opt,name=category"`
	xxx_hidden_Description *string                `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_Budget      *string                `protobuf:"bytes,4,opt,name=budget"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateExpenseRequest) Reset() {
	*x = CreateExpenseRequest{}
	mi := &file_proto_expense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseRequest) ProtoMessage() {}

func (x *CreateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateExpenseRequest) GetAmount() string {
	if x != nil {
		if x.xxx_hidden_Amount != nil {
			return *x.xxx_hidden_Amount
		}
		return ""
	}
	return ""
}

func (x *CreateExpenseRequest) GetCategory() string {
	if x != nil {
		if x.xxx_hidden_Category != nil {
			return *x.xxx_hidden_Category
		}
		return ""
	}
	return ""
}

func (x *CreateExpenseRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *CreateExpenseRequest) GetBudget() string {
	if x != nil {
		if x.xxx_hidden_Budget != nil {
			return *x.xxx_hidden_Budget
		}
		return ""
	}
	return ""
}

func (x *CreateExpenseRequest) SetAmount(v string) {
	x.xxx_hidden_Amount = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *CreateExpenseRequest) SetCategory(v string) {
	x.xxx_hidden_Category = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *CreateExpenseRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *CreateExpenseRequest) SetBudget(v string) {
	x.xxx_hidden_Budget = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *CreateExpenseRequest) HasAmount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateExpenseRequest) HasCategory() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateExpenseRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateExpenseRequest) HasBudget() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateExpenseRequest) ClearAmount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Amount = nil
}

func (x *CreateExpenseRequest) ClearCategory() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Category = nil
}

func (x *CreateExpenseRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *CreateExpenseRequest) ClearBudget() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Budget = nil
}

type CreateExpenseRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Amount      *string
	Category    *string
	Description *string
	Budget      *string
}

func (b0 CreateExpenseRequest_builder) Build() *CreateExpenseRequest {
	m0 := &CreateExpenseRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Amount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Amount = b.Amount
	}
	if b.Category != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Category = b.Category
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Description = b.Description
	}
	if b.Budget != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Budget = b.Budget
	}
	return m0
}

type CreateExpenseResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Expense *Expense               `protobuf:"bytes,1,opt,name=expense"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateExpenseResponse) Reset() {
	*x = CreateExpenseResponse{}
	mi := &file_proto_expense_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseResponse) ProtoMessage() {}

func (x *CreateExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateExpenseResponse) GetExpense() *Expense {
	if x != nil {
		return x.xxx_hidden_Expense
	}
	return nil
}

func (x *CreateExpenseResponse) SetExpense(v *Expense) {
	x.xxx_hidden_Expense = v
}

func (x *CreateExpenseResponse) HasExpense() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Expense != nil
}

func (x *CreateExpenseResponse) ClearExpense() {
	x.xxx_hidden_Expense = nil
}

type CreateExpenseResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Expense *Expense
}

func (b0 CreateExpenseResponse_builder) Build() *CreateExpenseResponse {
	m0 := &CreateExpenseResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Expense = b.Expense
	return m0
}

type GetExpensesRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Category    *string                `protobuf:"bytes,1,opt,name=category"`
	xxx_hidden_Date        *string                `protobuf:"bytes,2,opt,name=date"`
	xxx_hidden_Amount      *string                `protobuf:"bytes,3,opt,name=amount"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetExpensesRequest) Reset() {
	*x = GetExpensesRequest{}
	mi := &file_proto_expense_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpensesRequest) ProtoMessage() {}

func (x *GetExpensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetExpensesRequest) GetCategory() string {
	if x != nil {
		if x.xxx_hidden_Category != nil {
			return *x.xxx_hidden_Category
		}
		return ""
	}
	return ""
}

func (x *GetExpensesRequest) GetDate() string {
	if x != nil {
		if x.xxx_hidden_Date != nil {
			return *x.xxx_hidden_Date
		}
		return ""
	}
	return ""
}

func (x *GetExpensesRequest) GetAmount() string {
	if x != nil {
		if x.xxx_hidden_Amount != nil {
			return *x.xxx_hidden_Amount
		}
		return ""
	}
	return ""
}

func (x *GetExpensesRequest) SetCategory(v string) {
	x.xxx_hidden_Category = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *GetExpensesRequest) SetDate(v string) {
	x.xxx_hidden_Date = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *GetExpensesRequest) SetAmount(v string) {
	x.xxx_hidden_Amount = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *GetExpensesRequest) HasCategory() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetExpensesRequest) HasDate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetExpensesRequest) HasAmount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetExpensesRequest) ClearCategory() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Category = nil
}

func (x *GetExpensesRequest) ClearDate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Date = nil
}

func (x *GetExpensesRequest) ClearAmount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Amount = nil
}

type GetExpensesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Category *string
	Date     *string
	Amount   *string
}

func (b0 GetExpensesRequest_builder) Build() *GetExpensesRequest {
	m0 := &GetExpensesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Category != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Category = b.Category
	}
	if b.Date != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Date = b.Date
	}
	if b.Amount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Amount = b.Amount
	}
	return m0
}

type GetExpensesResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Expenses *[]*Expense            `protobuf:"bytes,1,rep,name=expenses"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetExpensesResponse) Reset() {
	*x = GetExpensesResponse{}
	mi := &file_proto_expense_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpensesResponse) ProtoMessage() {}

func (x *GetExpensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetExpensesResponse) GetExpenses() []*Expense {
	if x != nil {
		if x.xxx_hidden_Expenses != nil {
			return *x.xxx_hidden_Expenses
		}
	}
	return nil
}

func (x *GetExpensesResponse) SetExpenses(v []*Expense) {
	x.xxx_hidden_Expenses = &v
}

type GetExpensesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Expenses []*Expense
}

func (b0 GetExpensesResponse_builder) Build() *GetExpensesResponse {
	m0 := &GetExpensesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Expenses = &b.Expenses
	return m0
}

type GetExpenseRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetExpenseRequest) Reset() {
	*x = GetExpenseRequest{}
	mi := &file_proto_expense_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpenseRequest) ProtoMessage() {}

func (x *GetExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetExpenseRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *GetExpenseRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetExpenseRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetExpenseRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

type GetExpenseRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int64
}

func (b0 GetExpenseRequest_builder) Build() *GetExpenseRequest {
	m0 := &GetExpenseRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = *b.Id
	}
	return m0
}

type GetExpenseResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Expense *Expense               `protobuf:"bytes,1,opt,name=expense"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetExpenseResponse) Reset() {
	*x = GetExpenseResponse{}
	mi := &file_proto_expense_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpenseResponse) ProtoMessage() {}

func (x *GetExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetExpenseResponse) GetExpense() *Expense {
	if x != nil {
		return x.xxx_hidden_Expense
	}
	return nil
}

func (x *GetExpenseResponse) SetExpense(v *Expense) {
	x.xxx_hidden_Expense = v
}

func (x *GetExpenseResponse) HasExpense() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Expense != nil
}

func (x *GetExpenseResponse) ClearExpense() {
	x.xxx_hidden_Expense = nil
}

type GetExpenseResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Expense *Expense
}

func (b0 GetExpenseResponse_builder) Build() *GetExpenseResponse {
	m0 := &GetExpenseResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Expense = b.Expense
	return m0
}

type DeleteExpenseRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteExpenseRequest) Reset() {
	*x = DeleteExpenseRequest{}
	mi := &file_proto_expense_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseRequest) ProtoMessage() {}

func (x *DeleteExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteExpenseRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DeleteExpenseRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteExpenseRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteExpenseRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

type DeleteExpenseRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int64
}

func (b0 DeleteExpenseRequest_builder) Build() *DeleteExpenseRequest {
	m0 := &DeleteExpenseRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = *b.Id
	}
	return m0
}

type DeleteExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseResponse) Reset() {
	*x = DeleteExpenseResponse{}
	mi := &file_proto_expense_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseResponse) ProtoMessage() {}

func (x *DeleteExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteExpenseResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteExpenseResponse_builder) Build() *DeleteExpenseResponse {
	m0 := &DeleteExpenseResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_proto_expense_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetSummaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetSummaryRequest_builder) Build() *GetSummaryRequest {
	m0 := &GetSummaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetSummaryResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Expenses *[]*Expense            `protobuf:"bytes,1,rep,name=expenses"`
	xxx_hidden_Summary  *ExpenseSummary        `protobuf:"bytes,2,opt,name=summary"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetSummaryResponse) Reset() {
	*x = GetSummaryResponse{}
	mi := &file_proto_expense_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryResponse) ProtoMessage() {}

func (x *GetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSummaryResponse) GetExpenses() []*Expense {
	if x != nil {
		if x.xxx_hidden_Expenses != nil {
			return *x.xxx_hidden_Expenses
		}
	}
	return nil
}

func (x *GetSummaryResponse) GetSummary() *ExpenseSummary {
	if x != nil {
		return x.xxx_hidden_Summary
	}
	return nil
}

func (x *GetSummaryResponse) SetExpenses(v []*Expense) {
	x.xxx_hidden_Expenses = &v
}

func (x *GetSummaryResponse) SetSummary(v *ExpenseSummary) {
	x.xxx_hidden_Summary = v
}

func (x *GetSummaryResponse) HasSummary() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Summary != nil
}

func (x *GetSummaryResponse) ClearSummary() {
	x.xxx_hidden_Summary = nil
}

type GetSummaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Expenses []*Expense
	Summary  *ExpenseSummary
}

func (b0 GetSummaryResponse_builder) Build() *GetSummaryResponse {
	m0 := &GetSummaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Expenses = &b.Expenses
	x.xxx_hidden_Summary = b.Summary
	return m0
}

type ExpenseSummary struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TotalAmount *string                `protobuf:"bytes,1,opt,name=total_amount,json=totalAmount"`
	xxx_hidden_TotalBudget *string                `protobuf:"bytes,2,opt,name=total_budget,json=totalBudget"`
	xxx_hidden_Difference  *string                `protobuf:"bytes,3,opt,name=difference"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExpenseSummary) Reset() {
	*x = ExpenseSummary{}
	mi := &file_proto_expense_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseSummary) ProtoMessage() {}

func (x *ExpenseSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExpenseSummary) GetTotalAmount() string {
	if x != nil {
		if x.xxx_hidden_TotalAmount != nil {
			return *x.xxx_hidden_TotalAmount
		}
		return ""
	}
	return ""
}

func (x *ExpenseSummary) GetTotalBudget() string {
	if x != nil {
		if x.xxx_hidden_TotalBudget != nil {
			return *x.xxx_hidden_TotalBudget
		}
		return ""
	}
	return ""
}

func (x *ExpenseSummary) GetDifference() string {
	if x != nil {
		if x.xxx_hidden_Difference != nil {
			return *x.xxx_hidden_Difference
		}
		return ""
	}
	return ""
}

func (x *ExpenseSummary) SetTotalAmount(v string) {
	x.xxx_hidden_TotalAmount = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ExpenseSummary) SetTotalBudget(v string) {
	x.xxx_hidden_TotalBudget = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ExpenseSummary) SetDifference(v string) {
	x.xxx_hidden_Difference = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ExpenseSummary) HasTotalAmount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ExpenseSummary) HasTotalBudget() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ExpenseSummary) HasDifference() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ExpenseSummary) ClearTotalAmount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TotalAmount = nil
}

func (x *ExpenseSummary) ClearTotalBudget() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TotalBudget = nil
}

func (x *ExpenseSummary) ClearDifference() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Difference = nil
}

type ExpenseSummary_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TotalAmount *string
	TotalBudget *string
	Difference  *string
}

func (b0 ExpenseSummary_builder) Build() *ExpenseSummary {
	m0 := &ExpenseSummary{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TotalAmount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_TotalAmount = b.TotalAmount
	}
	if b.TotalBudget != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_TotalBudget = b.TotalBudget
	}
	if b.Difference != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Difference = b.Difference
	}
	return m0
}

var File_proto_expense_proto protoreflect.FileDescriptor

const file_proto_expense_proto_rawDesc = "" +
	"\n" +
	"\x13proto/expense.proto\x12\n" +
	"expense.v1\"\xa6\x01\n" +
	"\aExpense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06budget\x18\x05 \x01(\tR\x06budget\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x84\x01\n" +
	"\x14CreateExpenseRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\tR\x06budget\"F\n" +
	"\x15CreateExpenseResponse\x12-\n" +
	"\aexpense\x18\x01 \x01(\v2\x13.expense.v1.ExpenseR\aexpense\"\\\n" +
	"\x12GetExpensesRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"F\n" +
	"\x13GetExpensesResponse\x12/\n" +
	"\bexpenses\x18\x01 \x03(\v2\x13.expense.v1.ExpenseR\bexpenses\"#\n" +
	"\x11GetExpenseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x12GetExpenseResponse\x12-\n" +
	"\aexpense\x18\x01 \x01(\v2\x13.expense.v1.ExpenseR\aexpense\"&\n" +
	"\x14DeleteExpenseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x17\n" +
	"\x15DeleteExpenseResponse\"\x13\n" +
	"\x11GetSummaryRequest\"{\n" +
	"\x12GetSummaryResponse\x12/\n" +
	"\bexpenses\x18\x01 \x03(\v2\x13.expense.v1.ExpenseR\bexpenses\x124\n" +
	"\asummary\x18\x02 \x01(\v2\x1a.expense.v1.ExpenseSummaryR\asummary\"v\n" +
	"\x0eExpenseSummary\x12!\n" +
	"\ftotal_amount\x18\x01 \x01(\tR\vtotalAmount\x12!\n" +
	"\ftotal_budget\x18\x02 \x01(\tR\vtotalBudget\x12\x1e\n" +
	"\n" +
	"difference\x18\x03 \x01(\tR\n" +
	"difference2\xa6\x03\n" +
	"\x0eExpenseService\x12T\n" +
	"\rCreateExpense\x12 .expense.v1.CreateExpenseRequest\x1a!.expense.v1.CreateExpenseResponse\x12N\n" +
	"\vGetExpenses\x12\x1e.expense.v1.GetExpensesRequest\x1a\x1f.expense.v1.GetExpensesResponse\x12K\n" +
	"\n" +
	"GetExpense\x12\x1d.expense.v1.GetExpenseRequest\x1a\x1e.expense.v1.GetExpenseResponse\x12T\n" +
	"\rDeleteExpense\x12 .expense.v1.DeleteExpenseRequest\x1a!.expense.v1.DeleteExpenseResponse\x12K\n" +
	"\n" +
	"GetSummary\x12\x1d.expense.v1.GetSummaryRequest\x1a\x1e.expense.v1.GetSummaryResponseB\x16Z\x14expenses/proto/pb;pbb\beditionsp\xe9\a"

var file_proto_expense_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_expense_proto_goTypes = []any{
	(*Expense)(nil),               // 0: expense.v1.Expense
	(*CreateExpenseRequest)(nil),  // 1: expense.v1.CreateExpenseRequest
	(*CreateExpenseResponse)(nil), // 2: expense.v1.CreateExpenseResponse
	(*GetExpensesRequest)(nil),    // 3: expense.v1.GetExpensesRequest
	(*GetExpensesResponse)(nil),   // 4: expense.v1.GetExpensesResponse
	(*GetExpenseRequest)(nil),     // 5: expense.v1.GetExpenseRequest
	(*GetExpenseResponse)(nil),    // 6: expense.v1.GetExpenseResponse
	(*DeleteExpenseRequest)(nil),  // 7: expense.v1.DeleteExpenseRequest
	(*DeleteExpenseResponse)(nil), // 8: expense.v1.DeleteExpenseResponse
	(*GetSummaryRequest)(nil),     // 9: expense.v1.GetSummaryRequest
	(*GetSummaryResponse)(nil),    // 10: expense.v1.GetSummaryResponse
	(*ExpenseSummary)(nil),        // 11: expense.v1.ExpenseSummary
}
var file_proto_expense_proto_depIdxs = []int32{
	0,  // 0: expense.v1.CreateExpenseResponse.expense:type_name -> expense.v1.Expense
	0,  // 1: expense.v1.GetExpensesResponse.expenses:type_name -> expense.v1.Expense
	0,  // 2: expense.v1.GetExpenseResponse.expense:type_name -> expense.v1.Expense
	0,  // 3: expense.v1.GetSummaryResponse.expenses:type_name -> expense.v1.Expense
	11, // 4: expense.v1.GetSummaryResponse.summary:type_name -> expense.v1.ExpenseSummary
	1,  // 5: expense.v1.ExpenseService.CreateExpense:input_type -> expense.v1.CreateExpenseRequest
	3,  // 6: expense.v1.ExpenseService.GetExpenses:input_type -> expense.v1.GetExpensesRequest
	5,  // 7: expense.v1.ExpenseService.GetExpense:input_type -> expense.v1.GetExpenseRequest
	7,  // 8: expense.v1.ExpenseService.DeleteExpense:input_type -> expense.v1.DeleteExpenseRequest
	9,  // 9: expense.v1.ExpenseService.GetSummary:input_type -> expense.v1.GetSummaryRequest
	2,  // 10: expense.v1.ExpenseService.CreateExpense:output_type -> expense.v1.CreateExpenseResponse
	4,  // 11: expense.v1.ExpenseService.GetExpenses:output_type -> expense.v1.GetExpensesResponse
	6,  // 12: expense.v1.ExpenseService.GetExpense:output_type -> expense.v1.GetExpenseResponse
	8,  // 13: expense.v1.ExpenseService.DeleteExpense:output_type -> expense.v1.DeleteExpenseResponse
	10, // 14: expense.v1.ExpenseService.GetSummary:output_type -> expense.v1.GetSummaryResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_expense_proto_init() }
func file_proto_expense_proto_init() {
	if File_proto_expense_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_expense_proto_rawDesc), len(file_proto_expense_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_expense_proto_goTypes,
		DependencyIndexes: file_proto_expense_proto_depIdxs,
		MessageInfos:      file_proto_expense_proto_msgTypes,
	}.Build()
	File_proto_expense_proto = out.File
	file_proto_expense_proto_goTypes = nil
	file_proto_expense_proto_depIdxs = nil
}
