// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"expenses/internal/application/expense"
	"expenses/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceInterface creates a new instance of MockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceInterface {
	mock := &MockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceInterface is an autogenerated mock type for the ServiceInterface type
type MockServiceInterface struct {
	mock.Mock
}

type MockServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceInterface) EXPECT() *MockServiceInterface_Expecter {
	return &MockServiceInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Create(ctx context.Context, expense domain.Expense) (domain.Expense, error) {
	ret := _mock.Called(ctx, expense)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Expense
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Expense) (domain.Expense, error)); ok {
		return returnFunc(ctx, expense)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Expense) domain.Expense); ok {
		r0 = returnFunc(ctx, expense)
	} else {
		r0 = ret.Get(0).(domain.Expense)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Expense) error); ok {
		r1 = returnFunc(ctx, expense)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServiceInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - expense domain.Expense
func (_e *MockServiceInterface_Expecter) Create(ctx any, expense any) *MockServiceInterface_Create_Call {
	return &MockServiceInterface_Create_Call{Call: _e.mock.On("Create", ctx, expense)}
}

func (_c *MockServiceInterface_Create_Call) Run(run func(ctx context.Context, expense domain.Expense)) *MockServiceInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Expense
		if args[1] != nil {
			arg1 = args[1].(domain.Expense)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceInterface_Create_Call) Return(expense1 domain.Expense, err error) *MockServiceInterface_Create_Call {
	_c.Call.Return(expense1, err)
	return _c
}

func (_c *MockServiceInterface_Create_Call) RunAndReturn(run func(ctx context.Context, expense domain.Expense) (domain.Expense, error)) *MockServiceInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServiceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockServiceInterface_Expecter) Delete(ctx any, id any) *MockServiceInterface_Delete_Call {
	return &MockServiceInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockServiceInterface_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockServiceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceInterface_Delete_Call) Return(err error) *MockServiceInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockServiceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) GetAll(ctx context.Context, filter domain.Filter) ([]domain.Expense, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Expense
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Filter) ([]domain.Expense, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Filter) []domain.Expense); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Expense)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Filter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockServiceInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.Filter
func (_e *MockServiceInterface_Expecter) GetAll(ctx any, filter any) *MockServiceInterface_GetAll_Call {
	return &MockServiceInterface_GetAll_Call{Call: _e.mock.On("GetAll", ctx, filter)}
}

func (_c *MockServiceInterface_GetAll_Call) Run(run func(ctx context.Context, filter domain.Filter)) *MockServiceInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Filter
		if args[1] != nil {
			arg1 = args[1].(domain.Filter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceInterface_GetAll_Call) Return(expenses []domain.Expense, err error) *MockServiceInterface_GetAll_Call {
	_c.Call.Return(expenses, err)
	return _c
}

func (_c *MockServiceInterface_GetAll_Call) RunAndReturn(run func(ctx context.Context, filter domain.Filter) ([]domain.Expense, error)) *MockServiceInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) GetByID(ctx context.Context, id int64) (domain.Expense, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Expense
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (domain.Expense, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) domain.Expense); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Expense)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockServiceInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockServiceInterface_Expecter) GetByID(ctx any, id any) *MockServiceInterface_GetByID_Call {
	return &MockServiceInterface_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockServiceInterface_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockServiceInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceInterface_GetByID_Call) Return(expense domain.Expense, err error) *MockServiceInterface_GetByID_Call {
	_c.Call.Return(expense, err)
	return _c
}

func (_c *MockServiceInterface_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (domain.Expense, error)) *MockServiceInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpensesWithSummary provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) GetExpensesWithSummary(ctx context.Context) ([]domain.Expense, expense.ExpenseSummary, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExpensesWithSummary")
	}

	var r0 []domain.Expense
	var r1 expense.ExpenseSummary
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Expense, expense.ExpenseSummary, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Expense); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Expense)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) expense.ExpenseSummary); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(expense.ExpenseSummary)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockServiceInterface_GetExpensesWithSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpensesWithSummary'
type MockServiceInterface_GetExpensesWithSummary_Call struct {
	*mock.Call
}

// GetExpensesWithSummary is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceInterface_Expecter) GetExpensesWithSummary(ctx any) *MockServiceInterface_GetExpensesWithSummary_Call {
	return &MockServiceInterface_GetExpensesWithSummary_Call{Call: _e.mock.On("GetExpensesWithSummary", ctx)}
}

func (_c *MockServiceInterface_GetExpensesWithSummary_Call) Run(run func(ctx context.Context)) *MockServiceInterface_GetExpensesWithSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceInterface_GetExpensesWithSummary_Call) Return(expenses []domain.Expense, expenseSummary expense.ExpenseSummary, err error) *MockServiceInterface_GetExpensesWithSummary_Call {
	_c.Call.Return(expenses, expenseSummary, err)
	return _c
}

func (_c *MockServiceInterface_GetExpensesWithSummary_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Expense, expense.ExpenseSummary, error)) *MockServiceInterface_GetExpensesWithSummary_Call {
	_c.Call.Return(run)
	return _c
}
